#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 31 17:46:35 2021

@author: anmol
"""
# Importing the libraries
import numpy as np
import tensorflow as tf
import re
import time
 
#------ DATA PREPROCESSING ------ 
 
#------ Importing the dataset
lines = open('movie_lines.txt', encoding = 'utf-8', errors = 'ignore').read().split('\n')
conversations = open('movie_conversations.txt', encoding = 'utf-8', errors = 'ignore').read().split('\n')
 
#------ Creating a dictionary that maps each line and its id
id2line = {}
for line in lines:
    _line = line.split(' +++$+++ ')
    if len(_line) == 5:
        id2line[_line[0]] = _line[4]
 
#------ Creating a list of all of the conversations
conversations_ids = []
for conversation in conversations[:-1]:
    _conversation = conversation.split(' +++$+++ ')[-1][1:-1].replace("'", "").replace(" ", "")
    conversations_ids.append(_conversation.split(','))
# clearning the spaces and appostrophies

#------ Getting separately the questions and the answers
questions = []
answers = []
for conversation in conversations_ids:
    for i in range(len(conversation) - 1):
        questions.append(id2line[conversation[i]])
        answers.append(id2line[conversation[i+1]])
 
#------ Doing a first cleaning of the texts questions and answers
def clean_text(text):
    text = text.lower() # converts to lower
    text = re.sub(r"i'm", "i am", text) # sub does the replacing
    text = re.sub(r"he's", "he is", text)
    text = re.sub(r"she's", "she is", text)
    text = re.sub(r"that's", "that is", text)
    text = re.sub(r"what's", "what is", text)
    text = re.sub(r"where's", "where is", text)
    text = re.sub(r"how's", "how is", text)
    text = re.sub(r"\'ll", " will", text)
    text = re.sub(r"\'ve", " have", text)
    text = re.sub(r"\'re", " are", text)
    text = re.sub(r"\'d", " would", text)
    text = re.sub(r"n't", " not", text)
    text = re.sub(r"won't", "will not", text)
    text = re.sub(r"can't", "cannot", text)
    text = re.sub(r"let's", "let us", text)
    text = re.sub(r"[-()\"#/@;:<>{}`+=~|.!?,]", "", text)
    return text
 
#------ Cleaning the questions and saving them
clean_questions = []
for question in questions:
    clean_questions.append(clean_text(question))
 
#------ Cleaning the answers and saving them
clean_answers = []
for answer in answers:
    clean_answers.append(clean_text(answer))
 
#------ Filtering out the questions and answers that are too short or too long
# Not used currently
short_questions = []
short_answers = []
i = 0
for question in clean_questions:
    if 2 <= len(question.split()) <= 25:
        short_questions.append(question)
        short_answers.append(clean_answers[i])
    i += 1
clean_questions = []
clean_answers = []
i = 0
for answer in short_answers:
    if 2 <= len(answer.split()) <= 25:
        clean_answers.append(answer)
        clean_questions.append(short_questions[i])
    i += 1
 
#------ Creating a dictionary that maps each word to its number of occurrences
word2count = {}
for question in clean_questions:
    for word in question.split():
        if word not in word2count:
            word2count[word] = 1
        else:
            word2count[word] += 1
for answer in clean_answers:
    for word in answer.split():
        if word not in word2count:
            word2count[word] = 1
        else:
            word2count[word] += 1
 
#------ Creating two dictionaries that map the questions words and the answers words to a unique integer
# Not used currently
threshold_questions = 15
questionswords2int = {}
word_number = 0
for word, count in word2count.items():
    if count >= threshold_questions:
        questionswords2int[word] = word_number
        word_number += 1
threshold_answers = 15
answerswords2int = {}
word_number = 0
for word, count in word2count.items():
    if count >= threshold_answers:
        answerswords2int[word] = word_number
        word_number += 1
 
#------ Adding the last tokens to these two dictionaries
tokens = ['<PAD>', '<EOS>', '<OUT>', '<SOS>']
for token in tokens:
    questionswords2int[token] = len(questionswords2int) + 1
for token in tokens:
    answerswords2int[token] = len(answerswords2int) + 1
 
#------ Creating the inverse dictionary of the answerswords2int dictionary
answersints2word = {w_i: w for w, w_i in answerswords2int.items()}
#w_i is values of dictionary, w is the key
 
#------ Adding the End Of String token to the end of every answer
for i in range(len(clean_answers)):
    clean_answers[i] += ' <EOS>'
 
#------ Translating all the questions and the answers into integers 
#       and Replacing all the words that were filtered out by <OUT> 
questions_into_int = []
for question in clean_questions:
    ints = []
    for word in question.split():
        if word not in questionswords2int:
            ints.append(questionswords2int['<OUT>'])
        else:
            ints.append(questionswords2int[word])
    questions_into_int.append(ints)
    
answers_into_int = []
for answer in clean_answers:
    ints = []
    for word in answer.split():
        if word not in answerswords2int:
            ints.append(answerswords2int['<OUT>'])
        else:
            ints.append(answerswords2int[word])
    answers_into_int.append(ints)
 
#------ Sorting questions and answers by the length of questions
sorted_clean_questions = []
sorted_clean_answers = []
for length in range(1, 25 + 1):
    for i in enumerate(questions_into_int):
        if len(i[1]) == length:
            sorted_clean_questions.append(questions_into_int[i[0]])
            sorted_clean_answers.append(answers_into_int[i[0]])
 
 
 
########## PART 2 - BUILDING THE SEQ2SEQ MODEL ##########
 
 
 
#------ Creating placeholders for the inputs and the targets
def model_inputs():
    inputs = tf.compat.v1.placeholder(tf.int32, [None, None], name = 'input')
    # tf.compat.v1.placeholder : https://www.tensorflow.org/api_docs/python/tf/compat/v1/placeholder
    # Inserts a placeholder for a tensor that will be always fed.

    # Placeholders are basically variables that are used later.
    # int32 is the type of data that would input
    # the the inputs, 2D matrix in current case
    # name of input
    targets = tf.compat.v1.placeholder(tf.int32, [None, None], name = 'target')
    lr = tf.compat.v1.placeholder(tf.float32, name = 'learning_rate')
    keep_prob = tf.compat.v1.placeholder(tf.float32, name = 'keep_prob')
    # keep_prob : for dropout rate
    return inputs, targets, lr, keep_prob
 
#------ Preprocessing the targets
def preprocess_targets(targets, word2int, batch_size):
    left_side = tf.fill([batch_size, 1], word2int['<SOS>'])
    # tf.fill : https://www.tensorflow.org/api_docs/python/tf/fill
    # Creates a tensor filled with a scalar value.

    # batch_size = number of lines, we start with SOS token, basically its int value
    right_side = tf.strided_slice(targets, [0,0], [batch_size, -1], [1,1])
    # strided slice : extracts subset of a tensor (on what, starting point, end point, the slide while doing extraction)
    preprocessed_targets = tf.concat([left_side, right_side], 1)
    # 1 = horizontal concatenation
    return preprocessed_targets
 
#------ Creating the Encoder RNN
def encoder_rnn(rnn_inputs, rnn_size, num_layers, keep_prob, sequence_length):
    # stacked RNN
    # model inputs, number of input tensors, number of layers, keep prob parameter, list of length of question in each batch
    lstm = tf.contrib.rnn.BasicLSTMCell(rnn_size)
    # tf.contrib.rnn.BasicLSTMCell : https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/rnn_cell/BasicLSTMCell 
    # Basic LSTM recurrent network cell.
    
    lstm_dropout = tf.contrib.rnn.DropoutWrapper(lstm, input_keep_prob = keep_prob)
    # tf.contrib.rnn.DropoutWrapper : https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/rnn_cell/DropoutWrapper
    #Operator adding dropout to inputs and outputs of the given cell.

    encoder_cell = tf.contrib.rnn.MultiRNNCell([lstm_dropout] * num_layers)
    # tf.contrib.rnn.MultiRNNCell : https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/rnn_cell/MultiRNNCell
    # RNN cell composed sequentially of multiple simple cells.
    
    encoder_output, encoder_state = tf.nn.bidirectional_dynamic_rnn(cell_fw = encoder_cell,
                                                                    cell_bw = encoder_cell,
                                                                    sequence_length = sequence_length,
                                                                    inputs = rnn_inputs,
                                                                    dtype = tf.float32)
    # tf.nn.bidirectional_dynamic_rnn : https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/bidirectional_dynamic_rnn
    # Creates a dynamic version of bidirectional recurrent neural network. (deprecated)
    
    # two varilables as the bidirectional dynamic rnn will return 2 values
    # for a bidirectional rnn the forward and backward sizes should be same.
    return encoder_state
 
#------ Decoding the training set
def decode_training_set(encoder_state, decoder_cell, decoder_embedded_input, sequence_length, decoding_scope, output_function, keep_prob, batch_size):
    attention_states = tf.zeros([batch_size, 1, decoder_cell.output_size])
    attention_keys, attention_values, attention_score_function, attention_construct_function = tf.contrib.seq2seq.prepare_attention(attention_states, attention_option = "bahdanau", num_units = decoder_cell.output_size)
    # tf.contrib.seq2seq.prepare_attention : https://docs1.w3cub.com/tensorflow~python/tf/contrib/seq2seq/prepare_attention/
    # Prepare keys/values/functions for attention.
    
    training_decoder_function = tf.contrib.seq2seq.attention_decoder_fn_train(encoder_state[0], # got from previous function, 1 as we want the values
                                                                              attention_keys, # will be compared to the target states
                                                                              attention_values, # used to construct the context vectors
                                                                              attention_score_function, # compute the similaritiy between the keys and the target states
                                                                              attention_construct_function, # to build the attention state
                                                                              name = "attn_dec_train") # namescope for the deocder function
   # tf.contrib.seq2seq.attention_decoder_fn_train : https://docs1.w3cub.com/tensorflow~python/tf/contrib/seq2seq/attention_decoder_fn_train/
   # Attentional decoder function for dynamic_rnn_decoder during training.
       
    decoder_output, decoder_final_state, decoder_final_context_state = tf.contrib.seq2seq.dynamic_rnn_decoder(decoder_cell, # arguments of decoder cell
                                                                                                              training_decoder_function, # that we got in previous line
                                                                                                              decoder_embedded_input, # which is one of arguments of the funciton
                                                                                                              sequence_length,
                                                                                                              scope = decoding_scope)
    # tf.contrib.seq2seq.dynamic_rnn_decoder : https://docs1.w3cub.com/tensorflow~python/tf/contrib/seq2seq/dynamic_rnn_decoder/
    # Dynamic RNN decoder for a sequence-to-sequence model specified by RNNCell and decoder function.

    decoder_output_dropout = tf.nn.dropout(decoder_output, keep_prob)
    # tf.nn.dropout : https://www.tensorflow.org/api_docs/python/tf/nn/dropout
    # Computes dropout: randomly sets elements to zero to prevent overfitting.

    return output_function(decoder_output_dropout)
 
#------ Decoding the test/validation set
def decode_test_set(encoder_state, decoder_cell, decoder_embeddings_matrix, sos_id, eos_id, maximum_length, num_words, decoding_scope, output_function, keep_prob, batch_size):
    # encoder stated from above fucntion, cell of decoder, mappings from word to vector of real numbers, 
    attention_states = tf.zeros([batch_size, 1, decoder_cell.output_size])
    attention_keys, attention_values, attention_score_function, attention_construct_function = tf.contrib.seq2seq.prepare_attention(attention_states, attention_option = "bahdanau", num_units = decoder_cell.output_size)
    test_decoder_function = tf.contrib.seq2seq.attention_decoder_fn_inference(output_function,
                                                                              encoder_state[0],
                                                                              attention_keys,
                                                                              attention_values,
                                                                              attention_score_function,
                                                                              attention_construct_function,
                                                                              decoder_embeddings_matrix,
                                                                              sos_id,
                                                                              eos_id,
                                                                              maximum_length,
                                                                              num_words,
                                                                              name = "attn_dec_inf")
    # tf.contrib.seq2seq.attention_decoder_fn_inference : https://docs1.w3cub.com/tensorflow~python/tf/contrib/seq2seq/attention_decoder_fn_inference/
    # Attentional decoder function for dynamic_rnn_decoder during inference.

    test_predictions, decoder_final_state, decoder_final_context_state = tf.contrib.seq2seq.dynamic_rnn_decoder(decoder_cell,
                                                                                                                test_decoder_function,
                                                                                                                scope = decoding_scope)
    return test_predictions
 
#------ Creating the Decoder RNN
def decoder_rnn(decoder_embedded_input, decoder_embeddings_matrix, encoder_state, num_words, sequence_length, rnn_size, num_layers, word2int, keep_prob, batch_size):
    with tf.variable_scope("decoding") as decoding_scope:
        # tf.variable_scope : https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope
        # A context manager for defining ops that creates variables (layers).

        lstm = tf.contrib.rnn.BasicLSTMCell(rnn_size)
        lstm_dropout = tf.contrib.rnn.DropoutWrapper(lstm, input_keep_prob = keep_prob)
        decoder_cell = tf.contrib.rnn.MultiRNNCell([lstm_dropout] * num_layers)
        weights = tf.truncated_normal_initializer(stddev = 0.1) # associated to neurons of the fully connected layers
        # tf.truncated_normal_initializer : https://www.tensorflow.org/api_docs/python/tf/compat/v1/truncated_normal_initializer
        # Initializer that generates a truncated normal distribution.

        biases = tf.zeros_initializer()
        # tf.zeros_initializer : https://www.tensorflow.org/api_docs/python/tf/zeros_initializer
        # Initializer that generates tensors initialized to 0.

        output_function = lambda x: tf.contrib.layers.fully_connected(x,
                                                                      num_words,
                                                                      None, # for the normalizer
                                                                      scope = decoding_scope,
                                                                      weights_initializer = weights,
                                                                      biases_initializer = biases)
        # tf.contrib.layers.fully_connected : http://man.hubwiz.com/docset/TensorFlow.docset/Contents/Resources/Documents/api_docs/python/tf/contrib/layers/fully_connected.html
        # Adds a fully connected layer.

        training_predictions = decode_training_set(encoder_state,
                                                   decoder_cell,
                                                   decoder_embedded_input,
                                                   sequence_length,
                                                   decoding_scope,
                                                   output_function,
                                                   keep_prob,
                                                   batch_size)
        decoding_scope.reuse_variables()
        # we want to reuse variables that were used in this decoding scope
        test_predictions = decode_test_set(encoder_state,
                                           decoder_cell,
                                           decoder_embeddings_matrix,
                                           word2int['<SOS>'],
                                           word2int['<EOS>'],
                                           sequence_length - 1,
                                           num_words,
                                           decoding_scope,
                                           output_function,
                                           keep_prob,
                                           batch_size)
    return training_predictions, test_predictions
 
#------ Building the seq2seq model
def seq2seq_model(inputs, targets, keep_prob, batch_size, sequence_length, answers_num_words, questions_num_words, encoder_embedding_size, decoder_embedding_size, rnn_size, num_layers, questionswords2int):
    encoder_embedded_input = tf.contrib.layers.embed_sequence(inputs,
                                                              answers_num_words + 1,
                                                              encoder_embedding_size,
                                                              initializer = tf.random_uniform_initializer(0, 1))
    # tf.contrib.layers.embed_sequence : http://tensorflow.biotecan.com/python/Python_1.8/tensorflow.google.cn/api_docs/python/tf/contrib/layers/embed_sequence.html
    # Maps a sequence of symbols to a sequence of embeddings. Typical use case would be reusing embeddings between an encoder and decoder.
    
    encoder_state = encoder_rnn(encoder_embedded_input, rnn_size, num_layers, keep_prob, sequence_length)
    preprocessed_targets = preprocess_targets(targets, questionswords2int, batch_size)
    decoder_embeddings_matrix = tf.Variable(tf.random_uniform([questions_num_words + 1, decoder_embedding_size], 0, 1))
    # tf.random_uniform : https://www.tensorflow.org/api_docs/python/tf/random/uniform
    # Outputs random values from a uniform distribution.

    decoder_embedded_input = tf.nn.embedding_lookup(decoder_embeddings_matrix, preprocessed_targets)
    # tf.nn.embedding_lookup : https://www.tensorflow.org/api_docs/python/tf/nn/embedding_lookup
    # Looks up embeddings for the given ids from a list of tensors.

    training_predictions, test_predictions = decoder_rnn(decoder_embedded_input,
                                                         decoder_embeddings_matrix,
                                                         encoder_state,
                                                         questions_num_words,
                                                         sequence_length,
                                                         rnn_size,
                                                         num_layers,
                                                         questionswords2int,
                                                         keep_prob,
                                                         batch_size)
    return training_predictions, test_predictions
 
 
 
########## PART 3 - TRAINING THE SEQ2SEQ MODEL ##########
 
#------ Setting the Hyperparameters
epochs = 100
batch_size = 32
rnn_size = 1024
num_layers = 3
encoding_embedding_size = 1024
decoding_embedding_size = 1024
learning_rate = 0.001
learning_rate_decay = 0.9
min_learning_rate = 0.0001
keep_probability = 0.5
 
#------ Defining a session
tf.compat.v1.reset_default_graph()
#tf.reset_default_graph()
# tf.reset_default_graph : https://www.tensorflow.org/api_docs/python/tf/compat/v1/reset_default_graph
# Clears the default graph stack and resets the global default graph.

session = tf.compat.v1.InteractiveSession()

# session = tf.InteractiveSession()
# tf.InteractiveSession : https://www.tensorflow.org/api_docs/python/tf/compat/v1/InteractiveSession
# A TensorFlow Session for use in interactive contexts, such as a shell.
 
#------ Loading the model inputs
inputs, targets, lr, keep_prob = model_inputs()
# using the function made above
 
#------ Setting the sequence length
sequence_length = tf.compat.v1.placeholder_with_default(25, None, name = 'sequence_length')
# tf.compat.v1.placeholder_with_default : https://www.tensorflow.org/api_docs/python/tf/compat/v1/placeholder_with_default
# A placeholder op that passes through input when its output is not fed.5 
    
#------ Getting the shape of the inputs tensor
input_shape = tf.shape(inputs)
# tf.shape : https://www.tensorflow.org/api_docs/python/tf/shape
# Returns a tensor containing the shape of the input tensor.
 
#------ Getting the training and test predictions
training_predictions, test_predictions = seq2seq_model(tf.reverse(inputs, [-1]),
                                                       targets,
                                                       keep_prob,
                                                       batch_size,
                                                       sequence_length,
                                                       len(answerswords2int),
                                                       len(questionswords2int),
                                                       encoding_embedding_size,
                                                       decoding_embedding_size,
                                                       rnn_size,
                                                       num_layers,
                                                       questionswords2int)
 
#------ Setting up the Loss Error, the Optimizer and Gradient Clipping
with tf.name_scope("optimization"):
    # adam optimizer + gradient clipping to avoid exploding or vanishing gradient issues 
    loss_error = tf.contrib.seq2seq.sequence_loss(training_predictions,
                                                  targets,
                                                  tf.ones([input_shape[0], sequence_length])) # tensor of weights all initialised to 1
    # tf.contrib.seq2seq.sequence_loss : https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq/sequence_loss
    # Computes the weighted cross-entropy loss for a sequence of logits.

    optimizer = tf.train.AdamOptimizer(learning_rate)
    # tf.train.AdamOptimizer : https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/AdamOptimizer
    # Optimizer that implements the Adam algorithm.

    gradients = optimizer.compute_gradients(loss_error)
    clipped_gradients = [(tf.clip_by_value(grad_tensor, -5., 5.), grad_variable) for grad_tensor, grad_variable in gradients if grad_tensor is not None]
    # tf.clip_by_value : https://www.tensorflow.org/api_docs/python/tf/clip_by_value
    # Clips tensor values to a specified min and max.

    optimizer_gradient_clipping = optimizer.apply_gradients(clipped_gradients)
 
#------ Padding the sequences with the <PAD> token
def apply_padding(batch_of_sequences, word2int):
    max_sequence_length = max([len(sequence) for sequence in batch_of_sequences])
    return [sequence + [word2int['<PAD>']] * (max_sequence_length - len(sequence)) for sequence in batch_of_sequences]
 
#------ Splitting the data into batches of questions and answers
def split_into_batches(questions, answers, batch_size):
    for batch_index in range(0, len(questions) // batch_size): # // gives an integer
        start_index = batch_index * batch_size
        questions_in_batch = questions[start_index : start_index + batch_size]
        answers_in_batch = answers[start_index : start_index + batch_size]
        padded_questions_in_batch = np.array(apply_padding(questions_in_batch, questionswords2int))
        padded_answers_in_batch = np.array(apply_padding(answers_in_batch, answerswords2int))
        yield padded_questions_in_batch, padded_answers_in_batch
 
#------ Splitting the questions and answers into training and validation sets
training_validation_split = int(len(sorted_clean_questions) * 0.15)
training_questions = sorted_clean_questions[training_validation_split:]
training_answers = sorted_clean_answers[training_validation_split:]
validation_questions = sorted_clean_questions[:training_validation_split]
validation_answers = sorted_clean_answers[:training_validation_split]
 
#------ Training
batch_index_check_training_loss = 100
batch_index_check_validation_loss = ((len(training_questions)) // batch_size // 2) - 1
total_training_loss_error = 0
list_validation_loss_error = []
early_stopping_check = 0
early_stopping_stop = 100
checkpoint = "chatbot_weights.ckpt"
session.run(tf.global_variables_initializer())
for epoch in range(1, epochs + 1):
    for batch_index, (padded_questions_in_batch, padded_answers_in_batch) in enumerate(split_into_batches(training_questions, training_answers, batch_size)):
        starting_time = time.time()
        _, batch_training_loss_error = session.run([optimizer_gradient_clipping, loss_error], {inputs: padded_questions_in_batch,
                                                                                               targets: padded_answers_in_batch,
                                                                                               lr: learning_rate,
                                                                                               sequence_length: padded_answers_in_batch.shape[1],
                                                                                               keep_prob: keep_probability})
        total_training_loss_error += batch_training_loss_error
        ending_time = time.time()
        batch_time = ending_time - starting_time # training time
        if batch_index % batch_index_check_training_loss == 0:
            print('Epoch: {:>3}/{}, Batch: {:>4}/{}, Training Loss Error: {:>6.3f}, Training Time on 100 Batches: {:d} seconds'.format(epoch,
                                                                                                                                       epochs,
                                                                                                                                       batch_index,
                                                                                                                                       len(training_questions) // batch_size,
                                                                                                                                       total_training_loss_error / batch_index_check_training_loss,
                                                                                                                                       int(batch_time * batch_index_check_training_loss)))
             # :>3 = for selecting 3 figures 
             
            total_training_loss_error = 0
        if batch_index % batch_index_check_validation_loss == 0 and batch_index > 0:
            total_validation_loss_error = 0
            starting_time = time.time()
            for batch_index_validation, (padded_questions_in_batch, padded_answers_in_batch) in enumerate(split_into_batches(validation_questions, validation_answers, batch_size)):
                batch_validation_loss_error = session.run(loss_error, {inputs: padded_questions_in_batch,
                                                                       targets: padded_answers_in_batch,
                                                                       lr: learning_rate,
                                                                       sequence_length: padded_answers_in_batch.shape[1],
                                                                       keep_prob: 1})
                total_validation_loss_error += batch_validation_loss_error
            ending_time = time.time()
            batch_time = ending_time - starting_time
            average_validation_loss_error = total_validation_loss_error / (len(validation_questions) / batch_size)
            print('Validation Loss Error: {:>6.3f}, Batch Validation Time: {:d} seconds'.format(average_validation_loss_error, int(batch_time)))
            learning_rate *= learning_rate_decay
            if learning_rate < min_learning_rate:
                learning_rate = min_learning_rate
               
            # taking care of early stopping
            list_validation_loss_error.append(average_validation_loss_error)
            if average_validation_loss_error <= min(list_validation_loss_error):
                print('I speak better now!!')
                early_stopping_check = 0
                saver = tf.train.Saver()
                saver.save(session, checkpoint)
            else:
                print("Sorry I do not speak better, I need to practice more.")
                early_stopping_check += 1
                if early_stopping_check == early_stopping_stop:
                    break
    if early_stopping_check == early_stopping_stop:
        print("My apologies, I cannot speak better anymore. This is the best I can do.")
        break
print("Game Over")
 
 
 
########## PART 4 - TESTING THE SEQ2SEQ MODEL ##########
 
 
 
# Loading the weights and Running the session
checkpoint = "./chatbot_weights.ckpt"
session = tf.InteractiveSession()
session.run(tf.global_variables_initializer())
saver = tf.train.Saver()
saver.restore(session, checkpoint)
 
# Converting the questions from strings to lists of encoding integers
def convert_string2int(question, word2int):
    question = clean_text(question)
    return [word2int.get(word, word2int['<OUT>']) for word in question.split()]
 
# Setting up the chat
while(True):
    question = input("You: ")
    if question == 'Goodbye':
        break
    question = convert_string2int(question, questionswords2int)
    question = question + [questionswords2int['<PAD>']] * (25 - len(question))
    fake_batch = np.zeros((batch_size, 25))
    fake_batch[0] = question
    predicted_answer = session.run(test_predictions, {inputs: fake_batch, keep_prob: 0.5})[0]
    answer = ''
    for i in np.argmax(predicted_answer, 1):
        if answersints2word[i] == 'i':
            token = ' I'
        elif answersints2word[i] == '<EOS>':
            token = '.'
        elif answersints2word[i] == '<OUT>':
            token = 'out'
        else:
            token = ' ' + answersints2word[i]
        answer += token
        if token == '.':
            break
    print('ChatBot: ' + answer)